const LOGIN = 'LOGIN'
const LOGOUT = 'LOGOUT'
const ON_SEARCH = 'ON_SEARCH'
const SET_PILLS = 'SET_PILLS'
const FETCH_PILLS = 'FETCH_PILLS'
const ADD_PILL_LIST = 'ADD_PILL_LIST'
const ADD_PILL_TO_LIST = 'ADD_PILL_TO_LIST'
const DELETE_PILL_LIST = 'DELETE_PILL_LIST'
export {LOGIN ,LOGOUT, ON_SEARCH, SET_PILLS, FETCH_PILLS, ADD_PILL_LIST, ADD_PILL_TO_LIST, DELETE_PILL_LIST}