const LOGIN = 'LOGIN'
const SIGN_UP = 'SIGN_UP'
const ON_SEARCH = 'ON_SEARCH'
const SET_PILLS = 'SET_PILLS'
const FETCH_PILLS = 'FETCH_PILLS'

export {LOGIN ,SIGN_UP, ON_SEARCH, SET_PILLS, FETCH_PILLS}